/**
 * 
 */
package de.ingrid.importer.udk.strategy;

import de.ingrid.importer.udk.ImportDescriptor;
import de.ingrid.importer.udk.jdbc.JDBCConnectionProxy;
import de.ingrid.importer.udk.provider.DataProvider;

/**
 * @author Administrator
 * 
 */
public interface IDCStrategy {
	
	/** Key for sys_generic_key table to set/extract version of idc schema. */
	static String KEY_IDC_VERSION = "IDC_VERSION";

	// ALL VERSIONS/STRATEGIES EXECUTED IN STRATEGY WORKFLOW ! 

	/** initial version/strategy */
	static String VALUE_IDC_VERSION_102 = "1.0.2";
	/** FIX strategy (writes NO version) for fixing wrong syslists. ALSO INTEGRATED IN STRATEGY WORKFLOW */
	static String VALUE_IDC_VERSION_102_FIX_SYSLIST = "1.0.2_fix_syslist_100_101";
	/** SNS Spatial Type Update */
	static String VALUE_IDC_VERSION_102_SNS_SPATIAL_TYPE = "1.0.2_sns_spatial_type";
	/** INSPIRE update version/strategy */
	static String VALUE_IDC_VERSION_103 = "1.0.3";
	/** Single Strategy for fixing tree path attribute in object/address nodes ! */
	static String VALUE_IDC_VERSION_103_FIX_TREE_PATH = "1.0.3_fix_tree_path";
	/** IMPORT/EXPORT etc. version/strategy -> InGrid 2.0 internal release ! */
	static String VALUE_IDC_VERSION_104 = "1.0.4";
	/** Update INSPIRE themes version/strategy -> can be executed on its own ! */
	static String VALUE_IDC_VERSION_104_FIX_INSPIRE_THEMES = "1.0.4_fix_inspire_themes";
	/** Official InGrid 2.0 release with fixes, addons */
	static String VALUE_IDC_VERSION_105 = "1.0.5";
	/** Update country codelist to all countries -> can be executed on its own ! */
	static String VALUE_IDC_VERSION_105_FIX_COUNTRY_CODELIST = "1.0.5_fixCountryCodelist";
	/** Extend all VARCHAR to 255 */
	static String VALUE_IDC_VERSION_106 = "1.0.6";
	/** FIX strategy (writes NO version) for fixing syslists. ALSO INTEGRATED IN STRATEGY WORKFLOW */
	static String VALUE_IDC_VERSION_106_FIX_SYSLIST_INSPIRE = "1.0.6_fixSyslistInspire";
	/** Changes for Running on Oracle */
	static String VALUE_IDC_VERSION_107 = "1.0.7";
	/** InGrid 2.3: separate object_access and object_use */
	static String VALUE_IDC_VERSION_108 = "1.0.8";
	/** InGrid 2.3: split class 3 (services) into geographic services and non geographic services */
	static String VALUE_IDC_VERSION_109 = "1.0.9";
	/** CHECK strategy (writes NO version). ALSO INTEGRATED IN STRATEGY WORKFLOW !
	 * <br>InGrid 2.3: Check INSPIRE Objects on missing data and do protocol -> can be executed on its own !
	 * <br>SWITCH OF STRATEGY VERSION ! Strategy Version (first two digits) correlates now with InGrid 
	 * project version !!! */
	static String VALUE_IDC_VERSION_2_3_0_CHECK_INSPIRE_OBJECTS = "2.3.0_checkInspireObjects";
	/** InGrid 2.3: INSPIRE theme affects fields of Geoinformation/Karte.
	 * <br>SWITCH OF STRATEGY VERSION ! Strategy Version (first two digits) correlates now with InGrid 
	 * project version !!! */
	static String VALUE_IDC_VERSION_2_3_0 = "2.3.0";
	/** InGrid 2.3 NI: new write_subtree permission */
    static String VALUE_IDC_VERSION_2_3_1_ADD_SUBTREE_PERMISSION = "2.3.1_addSubtreePermission";
	/** InGrid 2.3 NI: connect user with multiple groups */
	static String VALUE_IDC_VERSION_2_3_1 = "2.3.1";
	

	/** Order of strategies to execute to obtain most recent IGC.
	 * Contains all according versions/strategies in ascending order.
	 * NOTICE: THESE VERSIONS ARE MAPPED TO STRATEGIES IN STRATEGY FACTORY !!! */
	static String[] STRATEGY_WORKFLOW = new String[] {
		VALUE_IDC_VERSION_102,
		VALUE_IDC_VERSION_102_FIX_SYSLIST,
		VALUE_IDC_VERSION_102_SNS_SPATIAL_TYPE,
		VALUE_IDC_VERSION_103,

		// Syslist csv have to be imported till version 104 ! in 104 and afterwards syslists are updated via java code !

		VALUE_IDC_VERSION_104,
		VALUE_IDC_VERSION_104_FIX_INSPIRE_THEMES,
		// InGrid 2.0 Release (including post fixes, addons)
		VALUE_IDC_VERSION_105,
		// At the moment strategy VALUE_IDC_VERSION_105_FIX_COUNTRY_CODELIST is NOT part of workflow !
		// So default is Europe and NOT all countries. The strategy can be executed on its own if all countries needed !
//		VALUE_IDC_VERSION_105_FIX_COUNTRY_CODELIST,
		VALUE_IDC_VERSION_106,
		VALUE_IDC_VERSION_106_FIX_SYSLIST_INSPIRE, // writes no Version
		VALUE_IDC_VERSION_107,
		VALUE_IDC_VERSION_108,
		VALUE_IDC_VERSION_109,
		VALUE_IDC_VERSION_2_3_0_CHECK_INSPIRE_OBJECTS, // writes no Version !
		VALUE_IDC_VERSION_2_3_0,
		VALUE_IDC_VERSION_2_3_1,
		VALUE_IDC_VERSION_2_3_1_ADD_SUBTREE_PERMISSION,
	};

		
	public void execute() throws Exception;

	public void setDataProvider(DataProvider data);

	public void setImportDescriptor(ImportDescriptor descriptor);

	public void setJDBCConnectionProxy(JDBCConnectionProxy jdbc);
	
	/**
	 * Get the IDC Version generated by this strategy (written into IDC catalog).
	 * After executing the strategy, the IDC structure is according to this version (but may have
	 * different data in tables, depending from strategy executed, e.g. full initial import or "empty" IDC).
	 * NOTICE: may be null, if strategy is independent from idc version, meaning can be executed any time.
	 * If null, then NO former strategies are executed if this is the target strategy. But this strategy
	 * can also be part of strategy workflow and will then be executed when "newer" target strategy is called !
	 * @return IDC version of catalog after execution. MAY RETURN NULL IF STRATEGY IS INDEPENDENT FROM
	 * VERSION AND CAN BE EXECUTED AT ANY TIME (no tracking and execution of strategies for obtaining
	 * former versions !)
	 */
	public String getIDCVersion();
}
